# These are supported funding model platforms

github: aaron-lee-hebert
buy_me_a_coffee: aaronleehebert

# Other options (uncomment and configure as needed):
# patreon: your-username
# ko_fi: your-username
# liberapay: your-username
# custom: ["https://your-custom-link.com"]
